
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FlightTracker.Provider
{

using System;
    using System.Collections.Generic;
    
public partial class AirPort
{

    public int Id { get; set; }

    public string OriginPort { get; set; }

    public string DestinationPort { get; set; }

    public string PortPair { get; set; }

}

}
